### PR TITLE
Modiied GAR room limit to 10. Also added layout support for up to 20 …

### PR DESCRIPTION
**Pull request by sherwinsim**
…viewers

### CODE REVIEW

**Comment by johache** [comment]
Looks pretty good.
Tested :
* on Chrome 47 and Firefox 41.0.2. 
* with and without MCU
* on my Mac Pro 

Chrome: runs quite smoothly on my Mac pro with 10 people
Firefox: systematic crash after 6 or 7 tabs. Error popup saying "ERROR: error: parser decode"
Checked GAR's code, seems to be a socket.io error , but might have a deeper root (from Let).

I'm getting to a point where even my Mac Pro has a hard time handling the trafic and CPU load :)
The MCU makes a gigantic difference in trafic load.

Graphic note: There is a black horizontal gap between each line, but there isn't one between each raw.
I think that we should pick either one and keep it. See attached screenshot:
screen shot 2015-11-04 at 4 41 49 pm

**Comment by sherwinsim** [comment]
Hmm interesting!
yeah I ha similar test results. the parser decode error is troubling, but I only get it after 9 people. I figure it's a client issue and not an actual GAR issue

Let me take a look at the code to i I can fix the small gap between the rows

**Comment by serrynaimo** [comment]
We shall make it a reasonable limit of users and make sure it works in all environments with all features. Screensharing is shaky even with just 3 people in Safari, doesn't work at all when using the Media Relay, Firefox doesn't go beyong 6 pax, so there's no point in increasing the number of participants to that limit as it can't live up to real-world use-cases or requires further restriction (e.g. disable screensharing with MCU).

**Comment by sherwinsim** [comment]
I'm cool with that.
I'll play around and try to figure out why screenshare is so flaky

**Comment by letchoo** [comment]
Will look into how we can resolve the screensharing rendering. The later versions of skylink relies mostly on renegotiation for reconnection, which likely does not require destroying the peerconnection. To see what we can improve on this commit

**Comment by letchoo** [comment]
Will work from here on how we can resolve the rest of the issues

**Pull request merged**
